# Stage 1: Base image.
FROM node:lts AS base

## Disable colour output from yarn to make logs easier to read.
ENV FORCE_COLOR=0
RUN corepack enable
WORKDIR /opt/docusaurus

# Stage 2a: Development mode.
FROM base AS dev
WORKDIR /opt/docusaurus
EXPOSE 3000
## Run the development server.
CMD [ -d "node_modules" ] && npm run start -- --host 0.0.0.0 --poll 1000 || npm install && npm run start -- --host 0.0.0.0 --poll 1000

# Stage 2b: Production build mode.
FROM base AS prod
WORKDIR /opt/docusaurus
## Copy over the source code.
COPY ./website /opt/docusaurus/
RUN npm ci
RUN npm run build

# Stage 3a: Serve with `docusaurus serve`.
FROM prod AS serve
EXPOSE 3000
## Run the production server.
CMD ["npm", "run", "serve", "--", "--host", "0.0.0.0", "--no-open"]

# Stage 3b: Serve with Caddy.
FROM caddy:2-alpine AS caddy
## Copy the Caddyfile.
COPY --from=prod /opt/docusaurus/Caddyfile /etc/caddy/Caddyfile
## Copy the Docusaurus build output.
COPY --from=prod /opt/docusaurus/build /var/docusaurus